Update GitHub Actions to enhance Maven build process
Improve the build workflow by adding clearer build stage logs and parallelizing sample project builds. Introduce error handling to ensure failures in any build stage are properly captured and reported.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -61,8 +61,28 @@ jobs:
       - name: Build sample projects with Maven
         run: |
           set -e
+
+          echo -e "☕️👷‍♂️Java Build"
+          mvn -B clean install -fae -Dno-format
+          
+          echo -e "🚀👷‍♂️Native Build" 
+          mvn -B install -ff -Dnative -Dquarkus.native.container-build -Dnative.surefire.skip
+          
+          echo -e "🖼Building Sample Projects"
+          set -e
+          pids=()
           for dir in samples/*/ ; do
-            (cd "$dir" && ./mvnw -B verify) &
+          (cd "$dir" && ./mvnw -B -ff verify) &
+          pids+=($!)
           done
-          wait
+          
+          failure=0
+          for pid in "${pids[@]}"; do
+          wait "$pid" || failure=1
+          done
+          
+          if [ $failure -ne 0 ]; then
+          echo "At least one sample build failed."
+          exit 1
+          fi
 
